// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:expense_tracker/data/model/category.dart';
import 'package:expense_tracker/data/model/daily_progress.dart';
import 'package:expense_tracker/data/model/expense.dart';
import 'package:expense_tracker/data/model/goal.dart';
import 'package:expense_tracker/data/model/habit.dart';
import 'package:expense_tracker/data/model/income.dart';
import 'package:expense_tracker/data/model/loan.dart';
import 'package:expense_tracker/data/model/recurring.dart';
import 'package:expense_tracker/data/model/users.dart';
import 'package:expense_tracker/data/model/wallet.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(DailyProgressAdapter());
    registerAdapter(DocumentTypeAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(IncomeAdapter());
    registerAdapter(InterestTypeAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanCreditorTypeAdapter());
    registerAdapter(LoanDocumentAdapter());
    registerAdapter(LoanPaymentAdapter());
    registerAdapter(LoanPurposeAdapter());
    registerAdapter(LoanStatusAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(PaymentFrequencyAdapter());
    registerAdapter(RecurringAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WalletAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(DailyProgressAdapter());
    registerAdapter(DocumentTypeAdapter());
    registerAdapter(ExpenseAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(IncomeAdapter());
    registerAdapter(InterestTypeAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanCreditorTypeAdapter());
    registerAdapter(LoanDocumentAdapter());
    registerAdapter(LoanPaymentAdapter());
    registerAdapter(LoanPurposeAdapter());
    registerAdapter(LoanStatusAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(PaymentFrequencyAdapter());
    registerAdapter(RecurringAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WalletAdapter());
  }
}
