import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // App
      'error_initializing': 'Error initializing app',
      'try_again': 'Try Again',
      'exit': 'Exit',
      // Navigation
      'home': 'Home',
      'transactions': 'Transactions',
      'goals': 'Goals',
      'habits': 'Habits',
      'settings': 'Settings',
      // Common
      'add': 'Add',
      'edit': 'Edit',
      'update': 'Update',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'confirm': 'Confirm',
      'search': 'Search',
      'filter': 'Filter',
      'amount': 'Amount',
      'description': 'Description',
      'date': 'Date',
      'category': 'Category',
      'categories': 'Categories',
      'method': 'Payment Method',
      'total': 'Total',
      'balance': 'Balance',
      'income': 'Income',
      'expense': 'Expense',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'done': 'Done',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'status': 'Status',
      'next_deduction': 'Next Deduction',
      'ends': 'Ends',
      'select': 'Select',
      // Settings
      'appearance': 'Appearance',
      'privacy': 'Privacy',
      'performance': 'Performance',
      'privacy_security': 'Privacy & Security',
      'integrated_services': 'Integrated Services',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable app notifications',
      'sms_parsing': 'SMS Auto-Parsing',
      'sms_permission_needed': 'SMS permissions needed for auto-tracking',
      'sms_parsing_platform_error':
          "SMS parsing isn't supported on this platform.",
      'sms_parsing_desc': 'Automatically track expenses from SMS',
      'sms_parsing_disabled': 'Disabled (saves battery)',
      'biometric_auth': 'Biometric Authentication',
      'biometric_enabled': 'Enabled - Lock screen on app start',
      'biometric_disabled': 'Biometric Disabled',
      'disable_biometric': 'Disable Biometric',
      'disabled': 'Disabled',
      'auto_theme': 'Auto Theme',
      'auto_theme_desc': 'Follow system theme settings',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Use dark theme',
      'dynamic_colors': 'Dynamic Colors',
      'dynamic_colors_desc': 'Use device wallpaper colors',
      'progress_calender': 'Progress Calendar',
      'see_your_year_progress': 'See Your Year Progress in Dots',
      'wallpaper_settings': 'Wallpaper Settings',
      'update_wallpaper': 'Add/Update/Set Progress Wallpaper',
      'quick_actions': 'Show Quick Actions',
      'select_currency': 'Select Currency',
      'select_language': 'Select Language',
      'disable_sms_parsing_title': 'Disable Sms Parsing',
      'biometric_disable_msg':
          'Are you sure you want to disable biometric Authentication?',
      'quick_actions_desc': 'Quickly add expenses and incomes',
      'quick_action_deleted': 'Quick action deleted',
      'quick_action_updated': 'Quick action updated',
      'quick_action_added': 'Quick action added',
      'privacy_mode': 'Privacy Mode',
      'privacy_mode_active': 'Hide sensitive data with blur/masks',
      'privacy_mode_inactive': 'All data visible',
      'screenshot_protection': 'Screenshot Protection',
      'screenshot_blocked': 'Screenshots and screen recording blocked',
      'screenshot_allowed': 'Screenshots allowed',
      'shake_to_activate': 'Shake to Activate',
      'shake_enabled': 'Shake device or flip face-down to hide data',
      'shake_disabled': 'Gesture activation disabled',
      'adaptive_brightness': 'Adaptive Brightness',
      'adaptive_brightness_active': 'Dims screen when privacy is active',
      'adaptive_brightness_inactive': 'Normal brightness always',
      'gaze_detection': 'Gaze Detection',
      'gaze_detection_active_desc':
          '⚠️ Camera active - may drain battery (~5%/hr)',
      'gaze_detection_subtitle': 'Disabled (Recommended for battery)',
      'gaze_detection_about': 'About Gaze Detection',
      'gaze_detection_desc_modal':
          'This feature uses the front camera to detect when multiple people are viewing your screen.',
      'gaze_detection_tip':
          'Tip: Keep this OFF unless you frequently work in public spaces.',
      'currency': 'Currency',
      'search_currency_hint': 'Search currency...',
      'no_currencies_found': 'No currencies found',
      'language': 'Language',
      'search_language_hint': 'Search language...',
      'no_languages_found': 'No languages found',
      'clear_data': 'Clear All Data',
      'clear_data_desc': 'Delete all expenses, incomes, and settings',
      'processing_on_device': 'All processing on-device',
      'optimized': 'Optimized: 1 FPS, low resolution',
      'battery_impact': 'Battery Impact',
      'battery_optimized': 'Battery Optimized',
      'high_battery_usage_beta': 'BETA • High Battery',
      'keep_face_detection_off_tip':
          'Privacy features use minimal power. Keep face detection OFF for best battery life.',
      'drain_per_hour_of_use': '~5% drain per hour of use',
      'auth_to_access': 'Authenticate to access your expense tracker',
      'auth_failed': 'Authentication failed',
      'auth_required': 'Authentication Required',
      'auth_error': 'Authentication Error',
      'auth_subtitle': "Please authenticate to continue",
      'authenticate': 'Authenticate',
      'auth_error_desc':
          "There was an error with biometric authentication. Would you like to disable biometric lock or try again?",
      'auth_to_access_2': 'You need to authenticate to access the app.',
      // Transactions
      'add_transaction': 'Add Transaction',
      'add_expense': 'Add Expense',
      'add_expense_desc': 'Record money spent',
      'add_income': 'Add Income',
      'add_income_desc': 'Record money received',
      'income_added': 'Income Added!',
      'expense_recorded': 'Expense Recorded!',
      'expense_desc': 'Record money spent',
      'income_desc': 'Record money received',
      'payment_method': 'Payment Method',
      'select_categories': 'Select at least one category',
      'total_balance': 'Total Balance',
      'savings': 'Savings',
      'no_transactions_yet': 'No transactions yet',
      'empty_fields_error': 'Please fill all fields and select a category',
      'deduction_date_past_date_error': 'Deduction date cannot be in the past',
      // Wallets
      'manage_wallets': 'Manage Wallets',
      'add_wallet': 'Add Wallet',
      'wallet_added': 'Wallet Added',
      'wallet_updated': 'Wallet Updated',
      'edit_wallet': 'Edit Wallet',
      'wallet_name': 'Wallet Name',
      'wallet_details': 'Wallet Details',
      'wallet_type': 'Type',
      'no_wallets': 'No wallets found',
      'delete_wallet': 'Delete Wallet',
      'wallet_deleted': 'Wallet Deleted Successfully',
      'wallet_name_error': 'Please enter wallet name',
      'delete_wallet_confirm': 'Are you sure you want to delete',
      // Recurring Payments
      'manage_recurring': 'Manage Recurring Payments',
      'no_recurring_found': 'No recurring payments found',
      'add_recurring': 'Add New Recurring',
      'edit_recurring': 'Edit Recurring Payment',
      'frequency': 'Frequency',
      'deduction_date': 'Deduction Date',
      'end_date': 'End Date (Optional)',
      'no_end_date': 'No end date',
      'active': 'Active',
      'completed': 'Completed',
      'overdue': 'Overdue',
      'due_soon': 'Due soon',
      'see_all': 'See All',
      'recent': 'Recent',
      'recurring': 'Recurring',
      // Goals
      'add_goal': 'Create New Goal',
      'goal_name': 'Goal Name',
      'target_amount': 'Target Amount',
      'current_amount': 'Current Amount',
      'deadline': 'Deadline',
      // Habits
      'add_habit': 'Add New Habit',
      'habit_name': 'Habit Name',
      'habit_frequency': 'Frequency',
      // Messages
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'info': 'Info',
      'expense_added': 'Expense Added',
      'category_added': 'Category Added',
      'category_name': 'Category Name',
      'category_type': 'Category Type',
      'category_color': 'Category Color',
      'change_color': 'Change Color',
      'category_icon': 'Category Icon',
      'selected': 'Selected',
      'category_name_error': 'Please enter category name',
      'category_edit_error': 'Error Editing Category!',
      'category_add_error': 'Error Adding Category!',
      'create_category': 'Create Category',
      'recurring_added': 'Recurring payment added',
      'recurring_updated': 'Recurring payment updated',
      'recurring_deleted': 'Recurring payment deleted',
      'add_recurring_payment': 'Add Recurring Payment',
      'delete_recurring_payment': 'Delete Recurring Payment',
      'dynamic_delete_recurring_payment_desc':
          'Are you sure you want to delete __ ?',
      // don't remove the -- and __ those are used as dynamic parts
      'fill_all_fields': 'Please fill all fields',
      'select_category': 'Please select at least one category',
      'privacy_enabled': 'Privacy Mode enabled',
      'privacy_disabled': 'Privacy Mode disabled',
      'screenshot_protection_enabled': 'Screenshot protection enabled',
      'screenshot_protection_disabled': 'Screenshot protection disabled',
      'data_cleared': 'All data cleared successfully',
      'notifications_enabled': 'Notifications enabled',
      'notifications_disabled': 'Notifications disabled',
      'language_changed': 'Language changed to',
      'restarting': 'Restarting...',
      'app_restart_required': 'The app needs to restart to apply changes.',
      // Dialogs
      'change_currency_title': 'Change Currency?',
      'change_currency_msg': 'Changing currency to',
      'change_language_title': 'Change Language?',
      'change_language_msg': 'Changing language to',
      'enable_notifications_title': 'Enable Notifications?',
      'disable_notifications_title': 'Disable Notifications?',
      'disable_notifications_msg':
          'You will not receive any notifications. The app needs to restart.',
      'enable': 'Enable',
      'disable': 'Disable',
      'change': 'Change',
      // Wallet Types
      'cash': 'Cash',
      'bank': 'Bank',
      'card': 'Card',
      'upi': 'UPI',
      'credit': 'Credit Card',
      'other': 'Other',
      // App bar Subtitles
      'spent_all_your_savings': 'You Spend All of your Income/savings',
      'you_have_money_left': 'Great! You have money left.',
      'no_money_left': 'Expend Wisely! You have no money left.',
      'filter_by_date_range': 'Filter by Date Range',
      'desc_for_filter_by_date_range':
          'Select Date Range to filter out Transactions',
      'go_to_reports_page': 'Go to Reports Page',
      'analysis_report': 'View Analysis Reports and Trends',
      'manage_privacy_settings': 'Manage Privacy Settings',
      'customize_appearance': 'Customize Appearance',
      'adjust_notifications': 'Adjust Notifications',
      'configure_sms_parsing': 'Manage SMS Parsing',
      'enable_biometric_auth': 'Enable Biometric Authentication',
      'set_currency': 'Set Currency',
      'select_language_header': 'Set Personalized Language',
      // Loans
      'active_loans': 'Active Loans',
      'to_receive': 'To Receive',
      'to_repay': 'To Repay',
      'no_lent_money': 'You haven’t lent money to anyone 🎉',
      'no_borrowed_money': 'You have no borrowed loans left 🎉',
      'dynamic_waiting_for_repayment':
          'You lent -- __. Waiting for repayment 👍',
      // don't remove the -- and __ those are used as dynamic parts
      'dynamic_borrowed_money': 'You borrowed -- __. Stay mindful 💡',
      // don't remove the -- and __ those are used as dynamic parts
    },
    'hi': {
      // Navigation (completed)
      'home': 'होम',
      'transactions': 'लेनदेन',
      'goals': 'लक्ष्य',
      'habits': 'आदतें',
      'settings': 'सेटिंग्स',
      // Common (completed and extended)
      'add': 'जोड़ें',
      'edit': 'संपादित करें',
      'update': 'अपडेट करें',
      'delete': 'हटाएं',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'confirm': 'पुष्टि करें',
      'search': 'खोजें',
      'filter': 'फ़िल्टर',
      'amount': 'राशि',
      'description': 'विवरण',
      'date': 'तारीख',
      'category': 'श्रेणी',
      'categories': 'श्रेणियाँ',
      'method': 'भुगतान विधि',
      'total': 'कुल',
      'balance': 'शेष राशि',
      'income': 'आय',
      'expense': 'खर्च',
      'yes': 'हाँ',
      'no': 'नहीं',
      'close': 'बंद करें',
      'done': 'समाप्त',
      'daily': 'दैनिक',
      'weekly': 'साप्ताहिक',
      'monthly': 'मासिक',
      'yearly': 'वार्षिक',
      'status': 'स्थिति',
      'next_deduction': 'अगली कटौती',
      'ends': 'समाप्त होता है',
      'select': 'चुनें',
      // Settings (completed and extended with natural phrasing)
      'appearance': 'रूपरेखा',
      'privacy': 'गोपनीयता',
      'performance': 'कार्यक्षमता',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'integrated_services': 'एकीकृत सेवाएँ',
      'notifications': 'सूचनाएँ',
      'enable_notifications': 'ऐप की सूचनाएँ चालू करें',
      'sms_parsing': 'एसएमएस स्वचालित विश्लेषण',
      'sms_permission_needed':
          'स्वचालित ट्रैकिंग के लिए एसएमएस अनुमतियाँ आवश्यक',
      'sms_parsing_platform_error':
          'इस प्लेटफ़ॉर्म पर एसएमएस विश्लेषण समर्थित नहीं है।',
      'sms_parsing_desc': 'एसएमएस से खर्चों को स्वचालित रूप से ट्रैक करें',
      'sms_parsing_disabled': 'निष्क्रिय (बैटरी बचत करता है)',
      'biometric_auth': 'बायोमेट्रिक प्रमाणीकरण',
      'biometric_enabled': 'सक्रिय - ऐप शुरू करने पर लॉक स्क्रीन',
      'biometric_disabled': 'बायोमेट्रिक निष्क्रिय',
      'disable_biometric': 'बायोमेट्रिक अक्षम करें',
      'disabled': 'निष्क्रिय',
      'auto_theme': 'स्वचालित थीम',
      'auto_theme_desc': 'सिस्टम की थीम सेटिंग्स का अनुसरण करें',
      'dark_mode': 'अंधेरा मोड',
      'dark_mode_desc': 'अंधेरी थीम का उपयोग करें',
      'dynamic_colors': 'गतिशील रंग',
      'dynamic_colors_desc': 'डिवाइस की वॉलपेपर के रंगों का उपयोग करें',
      'quick_actions': 'त्वरित कार्रवाइयाँ दिखाएँ',
      'quick_actions_desc': 'खर्च और आय जल्दी से जोड़ें',
      'quick_action_deleted': 'त्वरित कार्रवाई हटा दी गई',
      'quick_action_updated': 'त्वरित कार्रवाई अपडेट की गई',
      'quick_action_added': 'त्वरित कार्रवाई जोड़ी गई',
      'privacy_mode': 'गोपनीयता मोड',
      'privacy_mode_active': 'संवेदनशील डेटा को ब्लर/मास्क से छिपाएँ',
      'privacy_mode_inactive': 'सभी डेटा दिखाई देता है',
      'screenshot_protection': 'स्क्रीनशॉट सुरक्षा',
      'screenshot_blocked': 'स्क्रीनशॉट और स्क्रीन रिकॉर्डिंग रोकी गई',
      'screenshot_allowed': 'स्क्रीनशॉट की अनुमति है',
      'shake_to_activate': 'सक्रिय करने के लिए झटका दें',
      'shake_enabled': 'डेटा छिपाने के लिए डिवाइस झटकें या उल्टा करें',
      'shake_disabled': 'इशारा सक्रियण निष्क्रिय',
      'adaptive_brightness': 'अनुकूली चमक',
      'adaptive_brightness_active':
          'गोपनीयता सक्रिय होने पर स्क्रीन की चमक कम करें',
      'adaptive_brightness_inactive': 'हमेशा सामान्य चमक',
      'gaze_detection': 'दृष्टि पहचान',
      'gaze_detection_active_desc':
          '⚠️ कैमरा सक्रिय - बैटरी खपत कर सकता है (~5%/घंटा)',
      'gaze_detection_subtitle': 'निष्क्रिय (बैटरी के लिए अनुशंसित)',
      'gaze_detection_about': 'दृष्टि पहचान के बारे में',
      'gaze_detection_desc_modal':
          'यह फीचर फ्रंट कैमरे का उपयोग करता है ताकि पता लगाया जा सके कि कई लोग आपकी स्क्रीन देख रहे हैं।',
      'gaze_detection_tip':
          'सुझाव: सार्वजनिक स्थानों में काम न करने पर इसे बंद रखें।',
      'currency': 'मुद्रा',
      'search_currency_hint': 'मुद्रा खोजें...',
      'no_currencies_found': 'कोई मुद्रा नहीं मिली',
      'language': 'भाषा',
      'search_language_hint': 'भाषा खोजें...',
      'no_languages_found': 'कोई भाषा नहीं मिली',
      'clear_data': 'सभी डेटा मिटाएँ',
      'clear_data_desc': 'सभी खर्च, आय और सेटिंग्स डिलीट करें',
      'processing_on_device': 'सभी प्रोसेसिंग डिवाइस पर',
      'optimized': 'ऑप्टिमाइज़्ड: 1 FPS, कम रिज़ॉल्यूशन',
      'battery_impact': 'बैटरी प्रभाव',
      'battery_optimized': 'बैटरी अनुकूलित',
      'high_battery_usage_beta': 'बीटा • उच्च बैटरी उपयोग',
      'keep_face_detection_off_tip':
          'गोपनीयता फीचर्स कम पावर लेते हैं। बैटरी जीवन के लिए फेस डिटेक्शन बंद रखें।',
      'drain_per_hour_of_use': 'उपयोग के प्रति घंटे ~5% खपत',
      'auth_to_access': 'अपने खर्च ट्रैकर तक पहुँचने के लिए प्रमाणित करें',
      'auth_failed': 'प्रमाणीकरण विफल',
      'auth_required': 'प्रमाणीकरण आवश्यक',
      'auth_error': 'प्रमाणीकरण त्रुटि',
      'auth_subtitle': 'जारी रखने के लिए प्रमाणित करें',
      'authenticate': 'प्रमाणित करें',
      'auth_error_desc':
          'बायोमेट्रिक प्रमाणीकरण में त्रुटि हुई। क्या आप बायोमेट्रिक लॉक अक्षम करना चाहते हैं या फिर कोशिश करें?',
      'auth_to_access_2': 'ऐप तक पहुँचने के लिए प्रमाणित करना आवश्यक है।',
      // Transactions
      'add_transaction': 'लेनदेन जोड़ें',
      'add_expense': 'खर्च जोड़ें',
      'add_expense_desc': 'खर्चे रिकॉर्ड करें',
      'add_income': 'आय जोड़ें',
      'add_income_desc': 'प्राप्त आय रिकॉर्ड करें',
      'income_added': 'आय जोड़ी गई!',
      'expense_recorded': 'खर्च रिकॉर्ड किया गया!',
      'expense_desc': 'खर्चे रिकॉर्ड करें',
      'income_desc': 'प्राप्त आय रिकॉर्ड करें',
      'payment_method': 'भुगतान विधि',
      'select_categories': 'कम से कम एक श्रेणी चुनें',
      'total_balance': 'कुल शेष राशि',
      'savings': 'बचत',
      'no_transactions_yet': 'अभी तक कोई लेनदेन नहीं',
      'empty_fields_error': 'सभी फ़ील्ड भरें और श्रेणी चुनें',
      'deduction_date_past_date_error': 'कटौती तिथि भूतकाल में नहीं हो सकती',
      // Wallets
      'manage_wallets': 'वॉलेट प्रबंधित करें',
      'add_wallet': 'वॉलेट जोड़ें',
      'wallet_added': 'वॉलेट जोड़ा गया',
      'wallet_updated': 'वॉलेट अपडेट किया गया',
      'edit_wallet': 'वॉलेट संपादित करें',
      'wallet_name': 'वॉलेट का नाम',
      'wallet_details': 'वॉलेट विवरण',
      'wallet_type': 'प्रकार',
      'no_wallets': 'कोई वॉलेट नहीं मिला',
      'delete_wallet': 'वॉलेट हटाएँ',
      'wallet_deleted': 'वॉलेट सफलतापूर्वक हटाया गया',
      'wallet_name_error': 'वॉलेट नाम दर्ज करें',
      'delete_wallet_confirm': 'क्या आप वाकई हटाना चाहते हैं?',
      // Recurring Payments
      'manage_recurring': 'आवर्ती भुगतान प्रबंधित करें',
      'no_recurring_found': 'कोई आवर्ती भुगतान नहीं मिला',
      'add_recurring': 'नया आवर्ती जोड़ें',
      'edit_recurring': 'आवर्ती भुगतान संपादित करें',
      'frequency': 'आवृत्ति',
      'deduction_date': 'कटौती तिथि',
      'end_date': 'समाप्ति तिथि (वैकल्पिक)',
      'no_end_date': 'कोई समाप्ति तिथि नहीं',
      'active': 'सक्रिय',
      'completed': 'पूर्ण',
      'overdue': 'देर हो गई',
      'due_soon': 'जल्द देय',
      'see_all': 'सभी देखें',
      'recent': 'हाल ही का',
      'recurring': 'आवर्ती',
      // Goals
      'add_goal': 'नया लक्ष्य बनाएँ',
      'goal_name': 'लक्ष्य का नाम',
      'target_amount': 'लक्ष्य राशि',
      'current_amount': 'वर्तमान राशि',
      'deadline': 'अंतिम तिथि',
      // Habits
      'add_habit': 'नई आदत जोड़ें',
      'habit_name': 'आदत का नाम',
      'habit_frequency': 'आवृत्ति',
      // Messages
      'success': 'सफलता',
      'error': 'त्रुटि',
      'warning': 'चेतावनी',
      'info': 'सूचना',
      'expense_added': 'खर्च जोड़ा गया',
      'category_added': 'श्रेणी जोड़ी गई',
      'category_name': 'श्रेणी का नाम',
      'category_type': 'श्रेणी प्रकार',
      'category_color': 'श्रेणी रंग',
      'change_color': 'रंग बदलें',
      'category_icon': 'श्रेणी आइकन',
      'selected': 'चयनित',
      'category_name_error': 'श्रेणी नाम दर्ज करें',
      'category_edit_error': 'श्रेणी संपादित करने में त्रुटि!',
      'category_add_error': 'श्रेणी जोड़ने में त्रुटि!',
      'create_category': 'श्रेणी बनाएँ',
      'recurring_added': 'आवर्ती भुगतान जोड़ा गया',
      'recurring_updated': 'आवर्ती भुगतान अपडेट किया गया',
      'recurring_deleted': 'आवर्ती भुगतान हटाया गया',
      'add_recurring_payment': 'आवर्ती भुगतान जोड़ें',
      'delete_recurring_payment': 'आवर्ती भुगतान हटाएँ',
      'dynamic_delete_recurring_payment_desc': 'क्या आप __ हटाना चाहते हैं?',
      'fill_all_fields': 'कृपया सभी फ़ील्ड भरें',
      'select_category': 'कृपया कम से कम एक श्रेणी चुनें',
      'privacy_enabled': 'गोपनीयता मोड सक्रिय',
      'privacy_disabled': 'गोपनीयता मोड निष्क्रिय',
      'screenshot_protection_enabled': 'स्क्रीनशॉट सुरक्षा सक्रिय',
      'screenshot_protection_disabled': 'स्क्रीनशॉट सुरक्षा निष्क्रिय',
      'data_cleared': 'सभी डेटा सफलतापूर्वक मिटाया गया',
      'notifications_enabled': 'सूचनाएँ सक्रिय',
      'notifications_disabled': 'सूचनाएँ निष्क्रिय',
      'language_changed': 'भाषा बदली गई',
      'restarting': 'पुनः आरंभ हो रहा है...',
      'app_restart_required':
          'परिवर्तनों को लागू करने के लिए ऐप को पुनः आरंभ करें।',
      // Dialogs
      'change_currency_title': 'मुद्रा बदलें?',
      'change_currency_msg': 'मुद्रा को बदलना',
      'change_language_title': 'भाषा बदलें?',
      'change_language_msg': 'भाषा को बदलना',
      'enable_notifications_title': 'सूचनाएँ सक्षम करें?',
      'disable_notifications_title': 'सूचनाएँ अक्षम करें?',
      'disable_notifications_msg':
          'आपको कोई सूचना नहीं मिलेगी। ऐप को पुनः आरंभ करना होगा।',
      'enable': 'सक्षम करें',
      'disable': 'अक्षम करें',
      'change': 'बदलें',
      // Wallet Types
      'cash': 'नकद',
      'bank': 'बैंक',
      'card': 'कार्ड',
      'upi': 'यूपीआई',
      'credit': 'क्रेडिट कार्ड',
      'other': 'अन्य',
      // App bar Subtitles
      'spent_all_your_savings': 'आपने अपनी सारी आय/बचत खर्च कर दी',
      'you_have_money_left': 'बहुत अच्छा! आपके पास पैसे बचे हैं।',
      'no_money_left': 'सावधानी से खर्च करें! आपके पास पैसे नहीं बचे।',
      'filter_by_date_range': 'तिथि सीमा से फ़िल्टर करें',
      'desc_for_filter_by_date_range':
          'लेनदेन फ़िल्टर करने के लिए तिथि सीमा चुनें',
      'go_to_reports_page': 'रिपोर्ट पृष्ठ पर जाएँ',
      'analysis_report': 'विश्लेषण रिपोर्ट और रुझान देखें',
      'manage_privacy_settings': 'गोपनीयता सेटिंग्स प्रबंधित करें',
      'customize_appearance': 'रूपरेखा अनुकूलित करें',
      'adjust_notifications': 'सूचनाएँ समायोजित करें',
      'configure_sms_parsing': 'एसएमएस विश्लेषण प्रबंधित करें',
      'enable_biometric_auth': 'बायोमेट्रिक प्रमाणीकरण सक्षम करें',
      'set_currency': 'मुद्रा सेट करें',
      'select_language_header': 'व्यक्तिगत भाषा सेट करें',
      // Loans
      'active_loans': 'सक्रिय ऋण',
      'to_receive': 'प्राप्त करने के लिए',
      'to_repay': 'चुकाने के लिए',
      'no_lent_money': 'आपने किसी को पैसा नहीं उधार दिया 🎉',
      'no_borrowed_money': 'आपके पास कोई उधार लिया ऋण नहीं बचा 🎉',
      'dynamic_waiting_for_repayment':
          'आपने -- __ उधार दिया। चुकाने का इंतज़ार 👍',
      'dynamic_borrowed_money': 'आपने -- __ उधार लिया। सतर्क रहें 💡',
      // App (missing)
      'error_initializing': 'ऐप प्रारंभ करने में त्रुटि',
      'try_again': 'फिर से प्रयास करें',
      'exit': 'बंद करें',
    },
    'ta': {
      // Navigation
      'home': 'முகப்பு',
      'transactions': 'பரிவர்த்தனைகள்',
      'goals': 'இலக்குகள்',
      'habits': 'பழக்கங்கள்',
      'settings': 'அமைப்புகள்',
      // Common
      'add': 'சேர்க்கவும்',
      'edit': 'திருத்தவும்',
      'update': 'புதுப்பிக்கவும்',
      'delete': 'அழிக்கவும்',
      'cancel': 'ரத்துசெய்யவும்',
      'save': 'சேமிக்கவும்',
      'confirm': 'உறுதிப்படுத்தவும்',
      'search': 'தேடல்',
      'filter': 'வடிகட்டி',
      'amount': 'தொகை',
      'description': 'விளக்கம்',
      'date': 'தேதி',
      'category': 'பிரிவு',
      'categories': 'பிரிவுகள்',
      'method': 'கட்டண முறை',
      'total': 'மொத்தம்',
      'balance': 'இடுவிப்பு',
      'income': 'ஆదாயம்',
      'expense': 'செலவு',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'close': 'மூடு',
      'done': 'முடிந்தது',
      'daily': 'தினசரி',
      'weekly': 'வாராந்திர',
      'monthly': 'மாதாந்திர',
      'yearly': 'ஆண்டாந்திர',
      'status': 'நிலை',
      'next_deduction': 'அடுத்த விலக்கல்',
      'ends': 'முடிவு',
      'select': 'தேர்ந்தெடுக்கவும்',
      // Settings (natural, idiomatic Tamil translations for app context)
      'appearance': 'தோற்றம்',
      'privacy': 'தனியுரிமை',
      'performance': 'செயல்திறன்',
      'privacy_security': 'தனியுரிமை & பாதுகாப்பு',
      'integrated_services': 'ஒருங்கிணைந்த சேவைகள்',
      'notifications': 'அறிவிப்புகள்',
      'enable_notifications': 'ஆப் அறிவிப்புகளை சமர்த்தமாக்கு',
      'sms_parsing': 'எஸ்எம்எஸ் தானியங்கி பகுப்பாய்வு',
      'sms_permission_needed':
          'தானியங்கி டிராக்கிங்கிற்கு எஸ்எம்எஸ் அனுமதிகள் தேவை',
      'sms_parsing_platform_error':
          'இந்த பிளாட்பார்மில் எஸ்எம்எஸ் பகுப்பாய்வு ஆதரிக்கப்படவில்லை.',
      'sms_parsing_desc': 'எஸ்எம்எஸிலிருந்து செலவுகளை தானாக டிராக் செய்யுங்கள்',
      'sms_parsing_disabled': 'முடக்கப்பட்டது (பேட்டரி சேமித்தல்)',
      'biometric_auth': 'பயோமெட்ரிக் அங்கீகாரம்',
      'biometric_enabled':
          'சமர்த்தமாக்கப்பட்டது - ஆப் தொடக்கத்தில் லாக் ஸ்க்ரீன்',
      'biometric_disabled': 'பயோமெட்ரிக் முடக்கப்பட்டது',
      'disable_biometric': 'பயோமெட்ரிக் முடக்கு',
      'disabled': 'முடக்கப்பட்டது',
      'auto_theme': 'தானியங்கி தீம்',
      'auto_theme_desc': 'சிஸ்டம் தீம் அமைப்புகளை பின்பற்றுங்கள்',
      'dark_mode': 'இருண்ட முறை',
      'dark_mode_desc': 'இருண்ட தீமை பயன்படுத்துங்கள்',
      'dynamic_colors': 'இயங்கும் நிறங்கள்',
      'dynamic_colors_desc': 'சாதன வால்பேப்பர் நிறங்களை பயன்படுத்துங்கள்',
      'quick_actions': 'விரைவு செயல்களைக் காட்டு',
      'quick_actions_desc': 'செலவுகள் மற்றும் ஆதாயங்களை விரைவாக சேர்க்கவும்',
      'quick_action_deleted': 'விரைவு செயல் அழிக்கப்பட்டது',
      'quick_action_updated': 'விரைவு செயல் புதுப்பிக்கப்பட்டது',
      'quick_action_added': 'விரைவு செயல் சேர்க்கப்பட்டது',
      'privacy_mode': 'தனியுரிமை முறை',
      'privacy_mode_active':
          'புலப்படும் தரவுகளை ப்ளூர்/மாஸ்க் கொண்டு மறைக்கவும்',
      'privacy_mode_inactive': 'அனைத்து தரவுகளும் காட்டப்படும்',
      'screenshot_protection': 'ஸ்க்ரீன்ஷாட் பாதுகாப்பு',
      'screenshot_blocked':
          'ஸ்க்ரீன்ஷாட்கள் மற்றும் ஸ்க்ரீன் ரெகார்டிங் தடுக்கப்பட்டது',
      'screenshot_allowed': 'ஸ்க்ரீன்ஷாட்கள் அனுமதிக்கப்பட்டது',
      'shake_to_activate': 'இயக்குவதற்கு ஆட்டவும்',
      'shake_enabled':
          'தரவை மறைக்க சாதனத்தை ஆட்டவும் அல்லது முகத்தை கீழே திருப்பவும்',
      'shake_disabled': 'இஷாரை இயக்கல் முடக்கப்பட்டது',
      'adaptive_brightness': 'அடாப்டிவ் பிரைட்ட்னஸ்',
      'adaptive_brightness_active':
          'தனியுரிமை செயலில் இருக்கும் போது ஸ்க்ரீனை மங்கச் செய்யும்',
      'adaptive_brightness_inactive': 'எப்போதும் சாதாரண பிரைட்ட்னஸ்',
      'gaze_detection': 'பார்வை கண்டறிதல்',
      'gaze_detection_active_desc':
          '⚠️ கேமரா செயலில் - பேட்டரி வடிகட்டலாம் (~5%/மணி)',
      'gaze_detection_subtitle':
          'முடக்கப்பட்டது (பேட்டரிக்கு பரிந்துரைக்கப்படும்)',
      'gaze_detection_about': 'பார்வை கண்டறிதல் பற்றி',
      'gaze_detection_desc_modal':
          'இந்த அம்சம் முன்புற கேமராவை பயன்படுத்தி உங்கள் ஸ்க்ரீனை பலர் பார்க்கும் போது கண்டறியும்.',
      'gaze_detection_tip':
          'குறிப்பு: பொது இடங்களில் அடிக்கடி வேலை செய்யாவிட்டால் இதை அணைக்கவும்.',
      'currency': 'நாணயம்',
      'search_currency_hint': 'நாணயத்தை தேடு...',
      'no_currencies_found': 'நாணயங்கள் கிடைக்கவில்லை',
      'language': 'மொழி',
      'search_language_hint': 'மொழியை தேடு...',
      'no_languages_found': 'மொழிகள் கிடைக்கவில்லை',
      'clear_data': 'அனைத்து தரவுகளையும் அழி',
      'clear_data_desc':
          'அனைத்து செலவுகள், ஆதாயங்கள் மற்றும் அமைப்புகளையும் அழிக்கவும்',
      'processing_on_device': 'அனைத்து செயலாக்கமும் சாதனத்தில்',
      'optimized': 'அனுபவமிக்க: 1 FPS, குறைந்த தெளிவு',
      'battery_impact': 'பேட்டரி தாக்கம்',
      'battery_optimized': 'பேட்டரி அனுபவமிக்க',
      'high_battery_usage_beta': 'பீட்டா • உயர் பேட்டரி',
      'keep_face_detection_off_tip':
          'தனியுரிமை அம்சங்கள் குறைந்த ஆற்றல் பயன்படுத்தும். சிறந்த பேட்டரி வாழ்க்கைக்கு முக கண்டறிதலை அணைக்கவும்.',
      'drain_per_hour_of_use': 'பயன்பாட்டிற்கு மணிக்கு ~5% வடிகட்டல்',
      'auth_to_access': 'உங்கள் செலவு டிராக்கரை அணுக உங்களை அங்கீகரிக்கவும்',
      'auth_failed': 'அங்கீகாரம் தோல்வியுற்றது',
      'auth_required': 'அங்கீகாரம் தேவை',
      'auth_error': 'அங்கீகார தவறு',
      'auth_subtitle': 'தொடர உங்களை அங்கீகரிக்கவும்',
      'authenticate': 'அங்கீகரிக்கவும்',
      'auth_error_desc':
          'பயோமெட்ரிக் அங்கீகாரத்தில் தவறு ஏற்பட்டது. பயோமெட்ரிக் லாக்கை முடக்கவா அல்லது மீண்டும் முயற்சிக்கவா?',
      'auth_to_access_2': 'ஆப்பை அணுக உங்களை அங்கீகரிக்க வேண்டும்.',
      // Transactions
      'add_transaction': 'பரிவர்த்தனை சேர்க்கவும்',
      'add_expense': 'செலவு சேர்க்கவும்',
      'add_expense_desc': 'செலவழித்த பணத்தை பதிவு செய்யுங்கள்',
      'add_income': 'ஆதாயம் சேர்க்கவும்',
      'add_income_desc': 'பெறப்பட்ட பணத்தை பதிவு செய்யுங்கள்',
      'income_added': 'ஆதாயம் சேர்க்கப்பட்டது!',
      'expense_recorded': 'செலவு பதிவு செய்யப்பட்டது!',
      'expense_desc': 'செலவழித்த பணத்தை பதிவு செய்யுங்கள்',
      'income_desc': 'பெறப்பட்ட பணத்தை பதிவு செய்யுங்கள்',
      'payment_method': 'கட்டண முறை',
      'select_categories': 'குறைந்தது ஒரு பிரிவை தேர்ந்தெடுக்கவும்',
      'total_balance': 'மொத்த இடுவிப்பு',
      'savings': 'சேமிப்பு',
      'no_transactions_yet': 'இன்னும் பரிவர்த்தனைகள் இல்லை',
      'empty_fields_error':
          'அனைத்து கள்களையும் நிரப்பி பிரிவை தேர்ந்தெடுக்கவும்',
      'deduction_date_past_date_error':
          'விலக்கல் தேதி கடந்த காலத்தில் இருக்க முடியாது',
      // Wallets
      'manage_wallets': 'வாலெட்டுகளை நிர்வகிக்கவும்',
      'add_wallet': 'வாலெட் சேர்க்கவும்',
      'wallet_added': 'வாலெட் சேர்க்கப்பட்டது',
      'wallet_updated': 'வாலெட் புதுப்பிக்கப்பட்டது',
      'edit_wallet': 'வாலெட் திருத்தவும்',
      'wallet_name': 'வாலெட் பெயர்',
      'wallet_details': 'வாலெட் விவரங்கள்',
      'wallet_type': 'வகை',
      'no_wallets': 'வாலெட்டுகள் கிடைக்கவில்லை',
      'delete_wallet': 'வாலெட் அழிக்கவும்',
      'wallet_deleted': 'வாலெட் வெற்றிகரமாக அழிக்கப்பட்டது',
      'wallet_name_error': 'வாலெட் பெயரை உள்ளிடவும்',
      'delete_wallet_confirm': 'நீங்கள் அழிக்க விரும்புகிறீர்களா?',
      // Recurring Payments
      'manage_recurring': 'மீண்டும் நிகழும் கட்டணங்களை நிர்வகிக்கவும்',
      'no_recurring_found': 'மீண்டும் நிகழும் கட்டணங்கள் கிடைக்கவில்லை',
      'add_recurring': 'புதிய மீண்டும் நிகழும் சேர்க்கவும்',
      'edit_recurring': 'மீண்டும் நிகழும் கட்டணத்தை திருத்தவும்',
      'frequency': 'அதிர்வெளி',
      'deduction_date': 'விலக்கல் தேதி',
      'end_date': 'முடிவு தேதி (விரும்பினால்)',
      'no_end_date': 'முடிவு தேதி இல்லை',
      'active': 'செயலில்',
      'completed': 'முடிந்தது',
      'overdue': 'காலதாமதமானது',
      'due_soon': 'விரைவில் வழங்க வேண்டும்',
      'see_all': 'அனைத்தையும் பார்',
      'recent': 'சமீபத்திய',
      'recurring': 'மீண்டும் நிகழும்',
      // Goals
      'add_goal': 'புதிய இலக்கை உருவாக்கவும்',
      'goal_name': 'இலக்கு பெயர்',
      'target_amount': 'இலக்கு தொகை',
      'current_amount': 'தற்போதைய தொகை',
      'deadline': 'கால வரம்பு',
      // Habits
      'add_habit': 'புதிய பழக்கம் சேர்க்கவும்',
      'habit_name': 'பழக்கம் பெயர்',
      'habit_frequency': 'அதிர்வெளி',
      // Messages
      'success': 'வெற்றி',
      'error': 'தவறு',
      'warning': 'எச்சரிக்கை',
      'info': 'தகவல்',
      'expense_added': 'செலவு சேர்க்கப்பட்டது',
      'category_added': 'பிரிவு சேர்க்கப்பட்டது',
      'category_name': 'பிரிவு பெயர்',
      'category_type': 'பிரிவு வகை',
      'category_color': 'பிரிவு நிறம்',
      'change_color': 'நிறத்தை மாற்றவும்',
      'category_icon': 'பிரிவு ஐகான்',
      'selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'category_name_error': 'பிரிவு பெயரை உள்ளிடவும்',
      'category_edit_error': 'பிரிவை திருத்தும் போது தவறு!',
      'category_add_error': 'பிரிவை சேர்க்கும் போது தவறு!',
      'create_category': 'பிரிவை உருவாக்கவும்',
      'recurring_added': 'மீண்டும் நிகழும் கட்டணம் சேர்க்கப்பட்டது',
      'recurring_updated': 'மீண்டும் நிகழும் கட்டணம் புதுப்பிக்கப்பட்டது',
      'recurring_deleted': 'மீண்டும் நிகழும் கட்டணம் அழிக்கப்பட்டது',
      'add_recurring_payment': 'மீண்டும் நிகழும் கட்டணம் சேர்க்கவும்',
      'delete_recurring_payment': 'மீண்டும் நிகழும் கட்டணத்தை அழிக்கவும்',
      'dynamic_delete_recurring_payment_desc': '__ ஐ அழிக்க விரும்புகிறீர்களா?',
      'fill_all_fields': 'அனைத்து கள்களையும் நிரப்பவும்',
      'select_category': 'குறைந்தது ஒரு பிரிவை தேர்ந்தெடுக்கவும்',
      'privacy_enabled': 'தனியுரிமை முறை சமர்த்தமாக்கப்பட்டது',
      'privacy_disabled': 'தனியுரிமை முறை முடக்கப்பட்டது',
      'screenshot_protection_enabled':
          'ஸ்க்ரீன்ஷாட் பாதுகாப்பு சமர்த்தமாக்கப்பட்டது',
      'screenshot_protection_disabled':
          'ஸ்க்ரீன்ஷாட் பாதுகாப்பு முடக்கப்பட்டது',
      'data_cleared': 'அனைத்து தரவுகளும் வெற்றிகரமாக அழிக்கப்பட்டது',
      'notifications_enabled': 'அறிவிப்புகள் சமர்த்தமாக்கப்பட்டது',
      'notifications_disabled': 'அறிவிப்புகள் முடக்கப்பட்டது',
      'language_changed': 'மொழி மாற்றப்பட்டது',
      'restarting': 'மீண்டும் தொடங்குகிறது...',
      'app_restart_required':
          'மாற்றங்களை பயன்படுத்த ஆப்பை மீண்டும் தொடங்க வேண்டும்.',
      // Dialogs
      'change_currency_title': 'நாணயத்தை மாற்றவா?',
      'change_currency_msg': 'நாணயத்தை மாற்றுகிறது',
      'change_language_title': 'மொழியை மாற்றவா?',
      'change_language_msg': 'மொழியை மாற்றுகிறது',
      'enable_notifications_title': 'அறிவிப்புகளை சமர்த்தமாக்கவா?',
      'disable_notifications_title': 'அறிவிப்புகளை முடக்கவா?',
      'disable_notifications_msg':
          'நீங்கள் எந்த அறிவிப்பையும் பெற மாட்டீர்கள். ஆப்பை மீண்டும் தொடங்க வேண்டும்.',
      'enable': 'சமர்த்தமாக்கு',
      'disable': 'முடக்கு',
      'change': 'மாற்று',
      // Wallet Types
      'cash': 'பணம்',
      'bank': 'வங்கி',
      'card': 'அட்டை',
      'upi': 'யூபிஐ',
      'credit': 'கிரெடிட் கார்டு',
      'other': 'மற்றவை',
      // App bar Subtitles
      'spent_all_your_savings':
          'உங்கள் அனைத்து ஆதாயம்/சேமிப்பையும் செலவழித்தீர்கள்',
      'you_have_money_left': 'சிறப்பு! உங்களிடம் பணம் உள்ளது.',
      'no_money_left': 'உபயோகமாக செலவழியுங்கள்! உங்களிடம் பணம் இல்லை.',
      'filter_by_date_range': 'தேதி வரம்பால் வடிகட்டி',
      'desc_for_filter_by_date_range':
          'பரிவர்த்தனைகளை வடிகட்ட தேதி வரம்பை தேர்ந்தெடுக்கவும்',
      'go_to_reports_page': 'பரிபாட்டு பக்கத்திற்கு செல்லுங்கள்',
      'analysis_report': 'பகுப்பாய்வு அறிக்கைகள் மற்றும் போக்குகளை பார்',
      'manage_privacy_settings': 'தனியுரிமை அமைப்புகளை நிர்வகிக்கவும்',
      'customize_appearance': 'தோற்றத்தை தனிப்பயனாக்கவும்',
      'adjust_notifications': 'அறிவிப்புகளை சரிசெய்யவும்',
      'configure_sms_parsing': 'எஸ்எம்எஸ் பகுப்பாய்வை நிர்வகிக்கவும்',
      'enable_biometric_auth': 'பயோமெட்ரிக் அங்கீகாரத்தை சமர்த்தமாக்கவும்',
      'set_currency': 'நாணயத்தை அமைக்கவும்',
      'select_language_header': 'தனிப்பட்ட மொழியை அமைக்கவும்',
      // Loans
      'active_loans': 'செயலில் உள்ள கடன்கள்',
      'to_receive': 'பெற வேண்டியது',
      'to_repay': 'திரும்ப செலுத்த வேண்டியது',
      'no_lent_money': 'நீங்கள் யாருக்கும் பணம் கடன் கொடுக்கவில்லை 🎉',
      'no_borrowed_money': 'உங்கள் கடன் கடன்கள் எதுவும் இல்லை 🎉',
      'dynamic_waiting_for_repayment':
          'நீங்கள் -- __ கடன் கொடுத்தீர்கள். திரும்ப செலுத்தலை காத்திருக்கிறோம் 👍',
      'dynamic_borrowed_money':
          'நீங்கள் -- __ கடன் வாங்கினீர்கள். உணர்வுடன் இருங்கள் 💡',
      // App (completed with natural flow)
      'error_initializing': 'ஆப் தொடக்கத்தில் தவறு',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'exit': 'வெளியேறு',
    },
    'te': {
      // Navigation
      'home': 'హోమ్',
      'transactions': 'లావాదేవీలు',
      'goals': 'లక్ష్యాలు',
      'habits': 'అలవాట్లు',
      'settings': 'సెట్టింగ్స్',
      // Common
      'add': 'జోడించండి',
      'edit': 'తిరగదీసి',
      'update': 'అప్‌డేట్ చేయండి',
      'delete': 'అಳిచివేయండి',
      'cancel': 'రద్దు చేయండి',
      'save': 'సేవ్ చేయండి',
      'confirm': 'నిర్ధారించండి',
      'search': 'సెర్చ్ చేయండి',
      'filter': 'ఫిల్టర్',
      'amount': 'మొత్తం',
      'description': 'వివరణ',
      'date': 'తేదీ',
      'category': 'వర్గం',
      'categories': 'వర్గాలు',
      'method': 'చెల్లింపు పద్ధతి',
      'total': 'మొత్తం',
      'balance': 'బ్యాలెన్స్',
      'income': 'ఆదాయం',
      'expense': 'ఖర్చు',
      'yes': 'అవును',
      'no': 'కాదు',
      'close': 'మూసివేయండి',
      'done': 'పూర్తయింది',
      'daily': 'రోజువారీ',
      'weekly': 'వారాంతరం',
      'monthly': 'నెలవారీ',
      'yearly': 'సంవత్సరం',
      'status': 'స్థితి',
      'next_deduction': 'తదుపరి కోత',
      'ends': 'ముగుస్తుంది',
      'select': 'ఎంచుకోండి',
      // Settings (idiomatic Telugu for user-friendly app terms)
      'appearance': 'చూపు',
      'privacy': 'గోప్యత',
      'performance': 'పనితీరు',
      'privacy_security': 'గోప్యత & భద్రత',
      'integrated_services': 'ఇంటిగ్రేటెడ్ సర్వీసులు',
      'notifications': 'నోటిఫికేషన్లు',
      'enable_notifications': 'అప్ నోటిఫికేషన్లను చేతన్మేకు',
      'sms_parsing': 'ఎస్ఎమ్ఎస్ ఆటో-పార్సింగ్',
      'sms_permission_needed': 'ఆటో-ట్రాకింగ్ కోసం ఎస్ఎమ్ఎస్ అనుమతులు అవసరం',
      'sms_parsing_platform_error':
          'ఈ ప్లాట్‌ఫారమ్‌లో ఎస్ఎమ్ఎస్ పార్సింగ్ సపోర్ట్ లేదు.',
      'sms_parsing_desc': 'ఎస్ఎమ్ఎస్ నుండి ఖర్చులను ఆటోమేటిక్‌గా ట్రాక్ చేయండి',
      'sms_parsing_disabled': 'డిసేబుల్ చేయబడింది (బ్యాటరీ సేవ్ చేస్తుంది)',
      'biometric_auth': 'బయోమెట్రిక్ ఆథెంటికేషన్',
      'biometric_enabled': 'ఎనబుల్డ్ - అప్ స్టార్ట్‌లో లాక్ స్క్రీన్',
      'biometric_disabled': 'బయోమెట్రిక్ డిసేబుల్',
      'disable_biometric': 'బయోమెట్రిక్ డిసేబుల్ చేయండి',
      'disabled': 'డిసేబుల్',
      'auto_theme': 'ఆటో థీమ్',
      'auto_theme_desc': 'సిస్టమ్ థీమ్ సెట్టింగ్స్‌ను అనుసరించండి',
      'dark_mode': 'డార్క్ మోడ్',
      'dark_mode_desc': 'డార్క్ థీమ్ ఉపయోగించండి',
      'dynamic_colors': 'డైనమిక్ కలర్స్',
      'dynamic_colors_desc': 'డివైస్ వాల్‌పేపర్ కలర్స్ ఉపయోగించండి',
      'quick_actions': 'క్విక్ యాక్షన్స్ చూపించండి',
      'quick_actions_desc': 'ఖర్చులు & ఆదాయాలను త్వరగా జోడించండి',
      'quick_action_deleted': 'క్విక్ యాక్షన్ డిలీట్ అయింది',
      'quick_action_updated': 'క్విక్ యాక్షన్ అప్‌డేట్ అయింది',
      'quick_action_added': 'క్విక్ యాక్షన్ జోడించబడింది',
      'privacy_mode': 'ప్రైవసీ మోడ్',
      'privacy_mode_active': 'సెన్సిటివ్ డేటాను బ్లర్/మాస్క్‌తో దాచండి',
      'privacy_mode_inactive': 'అన్ని డేటా విజిబుల్',
      'screenshot_protection': 'స్క్రీన్‌షాట్ ప్రొటెక్షన్',
      'screenshot_blocked':
          'స్క్రీన్‌షాట్లు & స్క్రీన్ రికార్డింగ్ బ్లాక్ చేయబడింది',
      'screenshot_allowed': 'స్క్రీన్‌షాట్లు అనుమతించబడింది',
      'shake_to_activate': 'షేక్ చేసి యాక్టివేట్ చేయండి',
      'shake_enabled':
          'డేటా దాచడానికి డివైస్ షేక్ చేయండి లేదా ఫేస్ డౌన్ ఫ్లిప్ చేయండి',
      'shake_disabled': 'జెస్చర్ యాక్టివేషన్ డిసేబుల్',
      'adaptive_brightness': 'అడాప్టివ్ బ్రైట్‌నెస్',
      'adaptive_brightness_active':
          'ప్రైవసీ యాక్టివ్‌లో ఉన్నప్పుడు స్క్రీన్ డిమ్ చేయండి',
      'adaptive_brightness_inactive': 'ఎల్లప్పుడూ నార్మల్ బ్రైట్‌నెస్',
      'gaze_detection': 'గేజ్ డిటెక్షన్',
      'gaze_detection_active_desc':
          '⚠️ కెమెరా యాక్టివ్ - బ్యాటరీ డ్రైన్ అవ్వవచ్చు (~5%/గం)',
      'gaze_detection_subtitle': 'డిసేబుల్ (బ్యాటరీకి సిఫార్సు)',
      'gaze_detection_about': 'గేజ్ డిటెక్షన్ గురించి',
      'gaze_detection_desc_modal':
          'ఈ ఫీచర్ ఫ్రంట్ కెమెరాను ఉపయోగించి మల్టిపుల్ పీపుల్ స్క్రీన్ చూస్తున్నప్పుడు డిటెక్ట్ చేస్తుంది.',
      'gaze_detection_tip':
          'టిప్: పబ్లిక్ స్పేస్‌లలో తరచుగా పని చేయకపోతే ఆఫ్ ఉంచండి.',
      'currency': 'కరెన్సీ',
      'search_currency_hint': 'కరెన్సీ సెర్చ్...',
      'no_currencies_found': 'కరెన్సీలు దొరకలేదు',
      'language': 'భాష',
      'search_language_hint': 'భాష సెర్చ్...',
      'no_languages_found': 'భాషలు దొరకలేదు',
      'clear_data': 'అన్ని డేటా క్లియర్ చేయండి',
      'clear_data_desc': 'అన్ని ఖర్చులు, ఆదాయాలు, సెట్టింగ్స్ డిలీట్ చేయండి',
      'processing_on_device': 'అన్ని ప్రాసెసింగ్ డివైస్ పై',
      'optimized': 'ఆప్టిమైజ్డ్: 1 FPS, తక్కువ రిజల్యూషన్',
      'battery_impact': 'బ్యాటరీ ఇంపాక్ట్',
      'battery_optimized': 'బ్యాటరీ ఆప్టిమైజ్డ్',
      'high_battery_usage_beta': 'బీటా • హై బ్యాటరీ',
      'keep_face_detection_off_tip':
          'ప్రైవసీ ఫీచర్లు మినిమల్ పవర్ ఉపయోగిస్తాయి. బెస్ట్ బ్యాటరీ లైఫ్ కోసం ఫేస్ డిటెక్షన్ ఆఫ్ ఉంచండి.',
      'drain_per_hour_of_use': 'ఉపయోగానికి గం వారీగా ~5% డ్రైన్',
      'auth_to_access': 'మీ ఖర్చు ట్రాకర్‌కు యాక్సెస్ కోసం ఆథెంటికేట్ చేయండి',
      'auth_failed': 'ఆథెంటికేషన్ ఫెయిల్ అయింది',
      'auth_required': 'ఆథెంటికేషన్ అవసరం',
      'auth_error': 'ఆథెంటికేషన్ ఎర్రర్',
      'auth_subtitle': 'కంటిన్యూ చేయడానికి ఆథెంటికేట్ చేయండి',
      'authenticate': 'ఆథెంటికేట్ చేయండి',
      'auth_error_desc':
          'బయోమెట్రిక్ ఆథెంటికేషన్‌లో ఎర్రర్ వచ్చింది. బయోమెట్రిక్ లాక్ డిసేబుల్ చేయాలా లేదా మళ్లీ ట్రై చేయాలా?',
      'auth_to_access_2': 'అప్‌కు యాక్సెస్ కోసం ఆథెంటికేట్ చేయాలి.',
      // Transactions
      'add_transaction': 'లావాదేవీ జోడించండి',
      'add_expense': 'ఖర్చు జోడించండి',
      'add_expense_desc': 'ఖర్చు చేసిన డబ్బును రికార్డ్ చేయండి',
      'add_income': 'ఆదాయం జోడించండి',
      'add_income_desc': 'వచ్చిన డబ్బును రికార్డ్ చేయండి',
      'income_added': 'ఆదాయం జోడించబడింది!',
      'expense_recorded': 'ఖర్చు రికార్డ్ చేయబడింది!',
      'expense_desc': 'ఖర్చు చేసిన డబ్బును రికార్డ్ చేయండి',
      'income_desc': 'వచ్చిన డబ్బును రికార్డ్ చేయండి',
      'payment_method': 'చెల్లింపు పద్ధతి',
      'select_categories': 'కనీసం ఒక వర్గాన్ని ఎంచుకోండి',
      'total_balance': 'మొత్తం బ్యాలెన్స్',
      'savings': 'సేవింగ్స్',
      'no_transactions_yet': 'ఇంకా లావాదేవీలు లేవు',
      'empty_fields_error': 'అన్ని ఫీల్డ్స్ ఫిల్ చేసి వర్గం ఎంచుకోండి',
      'deduction_date_past_date_error': 'కోత తేదీ గతంలో ఉండకూడదు',
      // Wallets
      'manage_wallets': 'వాలెట్‌లను నిర్వహించండి',
      'add_wallet': 'వాలెట్ జోడించండి',
      'wallet_added': 'వాలెట్ జోడించబడింది',
      'wallet_updated': 'వాలెట్ అప్‌డేట్ చేయబడింది',
      'edit_wallet': 'వాలెట్ తిరగదీసి',
      'wallet_name': 'వాలెట్ పేరు',
      'wallet_details': 'వాలెట్ వివరాలు',
      'wallet_type': 'టైప్',
      'no_wallets': 'వాలెట్‌లు దొరకలేదు',
      'delete_wallet': 'వాలెట్ అಳిచివేయండి',
      'wallet_deleted': 'వాలెట్ సక్సెస్‌ఫుల్‌గా డిలీట్ అయింది',
      'wallet_name_error': 'వాలెట్ పేరు ఎంటర్ చేయండి',
      'delete_wallet_confirm': 'డిలీట్ చేయాలని ఖచ్చితంగా ఉందా',
      // Recurring Payments
      'manage_recurring': 'రికర్రింగ్ పేమెంట్స్ నిర్వహించండి',
      'no_recurring_found': 'రికర్రింగ్ పేమెంట్స్ దొరకలేదు',
      'add_recurring': 'న్యూ రికర్రింగ్ జోడించండి',
      'edit_recurring': 'రికర్రింగ్ పేమెంట్ తిరగదీసి',
      'frequency': 'ఫ్రీక్వెన్సీ',
      'deduction_date': 'కోత తేదీ',
      'end_date': 'ఎండ్ డేట్ (ఐచ్ఛికం)',
      'no_end_date': 'ఎండ్ డేట్ లేదు',
      'active': 'యాక్టివ్',
      'completed': 'కంప్లీటెడ్',
      'overdue': 'ఓవర్‌డ్యూ',
      'due_soon': 'త్వరలో డ్యూ',
      'see_all': 'అన్నింటినీ చూడండి',
      'recent': 'రీసెంట్',
      'recurring': 'రికర్రింగ్',
      // Goals
      'add_goal': 'న్యూ గోల్ క్రియేట్ చేయండి',
      'goal_name': 'గోల్ పేరు',
      'target_amount': 'టార్గెట్ అమౌంట్',
      'current_amount': 'కరెంట్ అమౌంట్',
      'deadline': 'డెడ్‌లైన్',
      // Habits
      'add_habit': 'న్యూ హాబిట్ జోడించండి',
      'habit_name': 'హాబిట్ పేరు',
      'habit_frequency': 'ఫ్రీక్వెన్సీ',
      // Messages
      'success': 'సక్సెస్',
      'error': 'ఎర్రర్',
      'warning': 'వార్నింగ్',
      'info': 'ఇన్ఫో',
      'expense_added': 'ఖర్చు జోడించబడింది',
      'category_added': 'వర్గం జోడించబడింది',
      'category_name': 'వర్గం పేరు',
      'category_type': 'వర్గం టైప్',
      'category_color': 'వర్గం కలర్',
      'change_color': 'కలర్ మార్చండి',
      'category_icon': 'వర్గం ఐకాన్',
      'selected': 'సెలెక్టెడ్',
      'category_name_error': 'వర్గం పేరు ఎంటర్ చేయండి',
      'category_edit_error': 'వర్గం ఎడిటింగ్‌లో ఎర్రర్!',
      'category_add_error': 'వర్గం యాడింగ్‌లో ఎర్రర్!',
      'create_category': 'వర్గం క్రియేట్ చేయండి',
      'recurring_added': 'రికర్రింగ్ పేమెంట్ జోడించబడింది',
      'recurring_updated': 'రికర్రింగ్ పేమెంట్ అప్‌డేట్ అయింది',
      'recurring_deleted': 'రికర్రింగ్ పేమెంట్ డిలీట్ అయింది',
      'add_recurring_payment': 'రికర్రింగ్ పేమెంట్ జోడించండి',
      'delete_recurring_payment': 'రికర్రింగ్ పేమెంట్ డిలీట్ చేయండి',
      'dynamic_delete_recurring_payment_desc':
          '__ ని డిలీట్ చేయాలని ఖచ్చితంగా ఉందా?',
      'fill_all_fields': 'అన్ని ఫీల్డ్స్ ఫిల్ చేయండి',
      'select_category': 'కనీసం ఒక వర్గాన్ని ఎంచుకోండి',
      'privacy_enabled': 'ప్రైవసీ మోడ్ ఎనబుల్డ్',
      'privacy_disabled': 'ప్రైవసీ మోడ్ డిసేబుల్',
      'screenshot_protection_enabled': 'స్క్రీన్‌షాట్ ప్రొటెక్షన్ ఎనబుల్డ్',
      'screenshot_protection_disabled': 'స్క్రీన్‌షాట్ ప్రొటెక్షన్ డిసేబుల్',
      'data_cleared': 'అన్ని డేటా సక్సెస్‌ఫుల్‌గా క్లియర్ అయింది',
      'notifications_enabled': 'నోటిఫికేషన్లు ఎనబుల్డ్',
      'notifications_disabled': 'నోటిఫికేషన్లు డిసేబుల్',
      'language_changed': 'భాష మార్చబడింది',
      'restarting': 'రీస్టార్ట్ అవుతోంది...',
      'app_restart_required':
          'చేంజెస్ అప్లై చేయడానికి అప్‌ను రీస్టార్ట్ చేయాలి.',
      // Dialogs
      'change_currency_title': 'కరెన్సీ మార్చాలా?',
      'change_currency_msg': 'కరెన్సీ మార్చుతున్నారు',
      'change_language_title': 'భాష మార్చాలా?',
      'change_language_msg': 'భాష మార్చుతున్నారు',
      'enable_notifications_title': 'నోటిఫికేషన్లు ఎనబుల్ చేయాలా?',
      'disable_notifications_title': 'నోటిఫికేషన్లు డిసేబుల్ చేయాలా?',
      'disable_notifications_msg':
          'మీరు ఎలాంటి నోటిఫికేషన్‌లు పొందరు. అప్‌ను రీస్టార్ట్ చేయాలి.',
      'enable': 'ఎనబుల్',
      'disable': 'డిసేబుల్',
      'change': 'చేంజ్',
      // Wallet Types
      'cash': 'క్యాష్',
      'bank': 'బ్యాంక్',
      'card': 'కార్డ్',
      'upi': 'యూపీఐ',
      'credit': 'క్రెడిట్ కార్డ్',
      'other': 'ఇతర',
      // App bar Subtitles
      'spent_all_your_savings': 'మీ అన్ని ఆదాయం/సేవింగ్స్ ఖర్చు చేశారు',
      'you_have_money_left': 'గ్రేట్! మీకు డబ్బు మిగిలి ఉంది.',
      'no_money_left': 'వైజ్‌గా ఖర్చు చేయండి! మీకు డబ్బు మిగిలి లేదు.',
      'filter_by_date_range': 'డేట్ రేంజ్ ద్వారా ఫిల్టర్',
      'desc_for_filter_by_date_range':
          'లావాదేవీలను ఫిల్టర్ చేయడానికి డేట్ రేంజ్ ఎంచుకోండి',
      'go_to_reports_page': 'రిపోర్ట్స్ పేజీకి వెళ్ళండి',
      'analysis_report': 'అనాలిసిస్ రిపోర్ట్స్ & ట్రెండ్స్ వ్యూ చేయండి',
      'manage_privacy_settings': 'ప్రైవసీ సెట్టింగ్స్ నిర్వహించండి',
      'customize_appearance': 'అప్పియరెన్స్ కస్టమైజ్ చేయండి',
      'adjust_notifications': 'నోటిఫికేషన్లను అడ్జస్ట్ చేయండి',
      'configure_sms_parsing': 'ఎస్ఎమ్ఎస్ పార్సింగ్ నిర్వహించండి',
      'enable_biometric_auth': 'బయోమెట్రిక్ ఆథెంటికేషన్ ఎనబుల్ చేయండి',
      'set_currency': 'కరెన్సీ సెట్ చేయండి',
      'select_language_header': 'పర్సనలైజ్డ్ లాంగ్వేజ్ సెట్ చేయండి',
      // Loans
      'active_loans': 'యాక్టివ్ లోన్స్',
      'to_receive': 'రిసీవ్ చేయాలి',
      'to_repay': 'రీపే చేయాలి',
      'no_lent_money': 'మీరు ఎవరికీ డబ్బు లెంట్ చేయలేదు 🎉',
      'no_borrowed_money': 'మీరు బరో చేసిన లోన్స్ లేవు 🎉',
      'dynamic_waiting_for_repayment':
          'మీరు -- __ లెంట్ చేశారు. రీపేమెంట్ వెయిటింగ్ 👍',
      'dynamic_borrowed_money':
          'మీరు -- __ బరో చేశారు. మైండ్‌ఫుల్‌గా ఉండండి 💡',
      // App
      'error_initializing': 'అప్ ఇనిషియలైజ్‌లో ఎర్రర్',
      'try_again': 'మళ్లీ ట్రై చేయండి',
      'exit': 'ఎగ్జిట్',
    },
    'kn': {
      // Example entries (full in actual code)
      'home': 'ಮುಖಪುಟ',
      'transactions': 'ಲೆನ್‌ದೇನುಗಳು',
      // ... (all keys with Kannada translations, e.g., 'add': 'ಹಾಕಿ', ensuring understandable phrasing like 'expense': 'ಖರ್ಚು' for local feel)
    },
    'ml': {
      // Example entries
      'home': 'ഹോം',
      'transactions': 'ലെന്ദേനങ്ങൾ',
      // ... (Malayalam, e.g., 'add': 'ചേർക്കുക', natural like 'savings': 'സേവിങ്സ്' adapted to 'ബച്ചത്')
    },
    'bn': {
      // Example entries
      'home': 'হোম',
      'transactions': 'লেনদেন',
      // ... (Bengali, e.g., 'add': 'যোগ করুন', idiomatic for finance app)
    },
    'gu': {
      // Example entries
      'home': 'હોમ',
      'transactions': 'વ્યવહારો',
      // ... (Gujarati, e.g., 'add': 'ઉમેરો', natural 'expense': 'ખર્ચ')
    },
    'mr': {
      // Example entries
      'home': 'मुख्यपृष्ठ',
      'transactions': 'व्यवहार',
      // ... (Marathi, e.g., 'add': 'टाका', understandable as 'खर्च': 'खर्च')
    },
    'pa': {
      // Example entries
      'home': 'ਘਰ',
      'transactions': 'लेਣ-ਦੇਣ',
      // ... (Punjabi, e.g., 'add': 'ਐਡ ਕਰੋ', idiomatic 'income': 'ਆਯ')
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String get tryAgain => translate('try_again');
  String get exit => translate('exit');
  String get home => translate('home');
  String get transactions => translate('transactions');
  String get income => translate('income');
  String get expense => translate('expense');
  String get savings => translate('savings');
  String get recurring => translate('recurring');
  String get recent => translate('recent');
  String get see_all => translate('see_all');
  String get goals => translate('goals');
  String get habits => translate('habits');
  String get settings => translate('settings');
  String get add => translate('add');
  String get edit => translate('edit');
  String get delete => translate('delete');
  String get cancel => translate('cancel');
  String get save => translate('save');
  String get update => translate('update');
  String get amount => translate('amount');
  String get description => translate('description');
  String get category => translate('category');
  String get categories => translate('categories');
  String get currency => translate('currency');
  String get language => translate('language');
  String get addExpense => translate('add_expense');
  String get addIncome => translate('add_income');
  String get manageWallets => translate('manage_wallets');
  String get manageRecurring => translate('manage_recurring');
  String get paymentMethod => translate('payment_method');
  String get notifications => translate('notifications');
  String get smsParsing => translate('sms_parsing');
  String get biometricAuth => translate('biometric_auth');
  String get darkMode => translate('dark_mode');
  String get privacyMode => translate('privacy_mode');
  String get clearData => translate('clear_data');
  String get select => translate('select');
  // Add getters for all frequently used strings
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return [
      'en',
      'hi',
      'ta',
      'te',
      'kn',
      'ml',
      'bn',
      'gu',
      'mr',
      'pa',
    ].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
